name: Build
on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
            echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
            yarn install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Lint
        run: yarn workspaces run lint
      - name: Build
        run: yarn workspaces run build
      - name: publish-react
        if: ${{ success() && github.event_name != 'pull_request' }}
        working-directory: ./packages/@manifoldxyz-react
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: publish-vue
        if: ${{ success() && github.event_name != 'pull_request' }}
        working-directory: ./packages/@manifoldxyz-vue
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
