name: Release
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]    
jobs:
  build_react_artifact:
    working-directory: packages/@manifoldxyz-react
    name: Build and upload artifact
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: react-dist
          path: dist
      - name: Release to github
        run: npm run release-github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    build_vue_artifact:
      working-directory: packages/@manifoldxyz-vue
      name: Build and upload artifact
      runs-on: ubuntu-latest
      timeout-minutes: 60
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16'

        - name: Install dependencies
          run: npm install

        - name: Build package
          run: npm run build

        - name: Upload artifact
          uses: actions/upload-artifact@v1
          with:
            name: vue-dist
            path: dist
        - name: Release to github
          run: npm run release-github
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # release_npm:
  #   name: Release to NPM
  #   needs: build_artifact
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   steps:
  #     - uses: actions/checkout@v2
  #     # Setup .npmrc file to publish to npm
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '16.x'
  #         registry-url: 'https://registry.npmjs.org'
  #     - run: npm install
  #       env:
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #     - name: Download react artifacts
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: react-dist
  #     - uses: JS-DevTools/npm-publish@v1
  #       with:
  #         token: ${{ secrets.NPM_TOKEN }}
  #         access: 'restricted'
  #     - name: Download vue artifacts
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: vue-dist
  #     - uses: JS-DevTools/npm-publish@v1
  #       with:
  #         token: ${{ secrets.NPM_TOKEN }}
  #         access: 'restricted'

